# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UrbsFrontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UrbsFrontend.Challenge')),
                ('jails', models.ManyToManyField(blank=True, related_name='jails', to='UrbsFrontend.Challenge')),
                ('next_challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UrbsFrontend.Step')),
            ],
        ),
        migrations.RemoveField(
            model_name='rtbranch',
            name='from_leaf',
        ),
        migrations.RemoveField(
            model_name='rtbranch',
            name='to_leaf',
        ),
        migrations.RemoveField(
            model_name='rtbranch',
            name='tree',
        ),
        migrations.RemoveField(
            model_name='rtleaf',
            name='challenge',
        ),
        migrations.RemoveField(
            model_name='rtleaf',
            name='tree',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='leaf',
        ),
        migrations.RemoveField(
            model_name='member',
            name='token',
        ),
        migrations.AddField(
            model_name='attempt',
            name='jail',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='pseudo',
            field=models.TextField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='location',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='RiddleTree',
        ),
        migrations.DeleteModel(
            name='RTBranch',
        ),
        migrations.DeleteModel(
            name='RTLeaf',
        ),
        migrations.AddField(
            model_name='attempt',
            name='step',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='UrbsFrontend.Step'),
            preserve_default=False,
        ),
    ]
