# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrbsFrontend', '0004_auto_20170101_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.TextField(max_length=200, unique=True),
        ),
    ]
