# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UrbsFrontend', '0005_auto_20170104_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='submitter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='UrbsFrontend.Member'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attempt',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='UrbsFrontend.Team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attempt',
            name='token_in',
            field=models.TextField(max_length=22),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='token_out',
            field=models.TextField(max_length=22),
        ),
    ]
