# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UrbsFrontend', '0006_auto_20170108_0011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='next_challenge',
            new_name='next_step',
        ),
        migrations.AddField(
            model_name='attempt',
            name='challenge',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='UrbsFrontend.Challenge'),
            preserve_default=False,
        ),
    ]
