# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrbsFrontend', '0007_auto_20170108_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='next_step',
        ),
        migrations.AddField(
            model_name='step',
            name='is_jail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='laumio',
            field=models.TextField(default='', max_length=4),
        ),
    ]
