# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrbsFrontend', '0009_challenge_is_jail'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
