# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UrbsFrontend', '0010_attempt_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='animation',
            name='params',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challenge',
            name='params',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='step',
            name='animation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='UrbsFrontend.Animation'),
            preserve_default=False,
        ),
    ]
