# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UrbsFrontend', '0012_auto_20170115_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UrbsFrontend.Challenge'),
        ),
        migrations.AlterField(
            model_name='team',
            name='step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UrbsFrontend.Step'),
        ),
    ]
